apiVersion: v1
kind: Pod
metadata:
  name: sql-for-yad-2
  labels:
    app: mysql
spec:
  containers:
  - name: sql-for-yad-2
    image: mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: z1z2z3z4z5
    # - name:
    #   value:

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

